### ISSUE TITLE
distribute_setup.py fails with 'sys_platform' is not defined error

### ISSUE THREAD

**Issue by garciastl** [magfest/ubersystem#1047]
To Whom It May Concern:

When trying to install the Ubersystem onto a development box following the instructions in INSTALL.manual.md, I receive a **NameError: name 'sys_platform' is not defined**. The full chain of events is enclosed below:

```
[noc@ubersystem-devel ~]$ ls -la
total 19124
drwx------.  3 noc  noc      4096 Apr  7 03:09 .
drwxr-xr-x.  3 root root       16 Apr  7 02:44 ..
-rw-------.  1 noc  noc       183 Apr  7 03:08 .bash_history
-rw-r--r--.  1 noc  noc        18 Mar  5 17:06 .bash_logout
-rw-r--r--.  1 noc  noc       193 Mar  5 17:06 .bash_profile
-rw-r--r--.  1 noc  noc       231 Mar  5 17:06 .bashrc
drwxrwxr-x. 16 noc  noc      4096 Apr  7 03:12 Python-3.4.3
-rw-rw-r--.  1 noc  noc  19554643 Feb 25 06:34 Python-3.4.3.tgz
[noc@ubersystem-devel ~]$ git clone https://github.com/magfest/ubersystem
Cloning into 'ubersystem'...
remote: Counting objects: 18321, done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 18321 (delta 0), reused 0 (delta 0), pack-reused 18302
Receiving objects: 100% (18321/18321), 57.06 MiB | 14.20 MiB/s, done.
Resolving deltas: 100% (6978/6978), done.
[noc@ubersystem-devel ~]$ cd ubersystem/
[noc@ubersystem-devel ubersystem]$ ls
conftest.py               INSTALL.md          selenium
DBUTILS.md                INSTALL.vagrant.md  setup.py
development-defaults.ini  LICENSE.txt         TESTING.HOWTO.md
distribute_setup.py       README.md           uber
INSTALL.manually.md       requirements.txt
[noc@ubersystem-devel ubersystem]$ python3
python3            python3.4-config   python3.4m-config
python3.4          python3.4m         python3-config
[noc@ubersystem-devel ubersystem]$ python3.4 -m venv env
[noc@ubersystem-devel ubersystem]$ ./env/bin/python --version
Python 3.4.3
[noc@ubersystem-devel ubersystem]$ ./env/bin/python distribute_setup.py
Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.49.tar.gz
Extracting in /tmp/tmpmroygxt6
Now working in /tmp/tmpmroygxt6/distribute-0.6.49
Installing Distribute
creating build
creating build/src
creating build/src/_markerlib
creating build/src/docs
creating build/src/docs/_templates
creating build/src/docs/_theme
creating build/src/docs/_theme/nature
creating build/src/docs/_theme/nature/static
creating build/src/docs/build
creating build/src/docs/build/html
creating build/src/docs/build/html/_sources
creating build/src/docs/build/html/_static
creating build/src/setuptools
creating build/src/setuptools/command
creating build/src/setuptools/tests
creating build/src/setuptools/tests/indexes
creating build/src/setuptools/tests/indexes/test_links_priority
creating build/src/setuptools/tests/indexes/test_links_priority/simple
creating build/src/setuptools/tests/indexes/test_links_priority/simple/foobar
creating build/src/tests
creating build/src/tests/shlib_test
copying setuptools/archive_util.py -> build/src/setuptools
copying setuptools/depends.py -> build/src/setuptools
copying setuptools/dist.py -> build/src/setuptools
copying setuptools/extension.py -> build/src/setuptools
copying setuptools/package_index.py -> build/src/setuptools
copying setuptools/py24compat.py -> build/src/setuptools
copying setuptools/sandbox.py -> build/src/setuptools
copying setuptools/script template (dev).py -> build/src/setuptools
copying setuptools/script template.py -> build/src/setuptools
copying setuptools/site-patch.py -> build/src/setuptools
copying setuptools/__init__.py -> build/src/setuptools
copying setuptools/tests/doctest.py -> build/src/setuptools/tests
copying setuptools/tests/py26compat.py -> build/src/setuptools/tests
copying setuptools/tests/server.py -> build/src/setuptools/tests
copying setuptools/tests/test_bdist_egg.py -> build/src/setuptools/tests
copying setuptools/tests/test_build_ext.py -> build/src/setuptools/tests
copying setuptools/tests/test_develop.py -> build/src/setuptools/tests
copying setuptools/tests/test_dist_info.py -> build/src/setuptools/tests
copying setuptools/tests/test_easy_install.py -> build/src/setuptools/tests
copying setuptools/tests/test_markerlib.py -> build/src/setuptools/tests
copying setuptools/tests/test_packageindex.py -> build/src/setuptools/tests
copying setuptools/tests/test_resources.py -> build/src/setuptools/tests
copying setuptools/tests/test_sandbox.py -> build/src/setuptools/tests
copying setuptools/tests/test_sdist.py -> build/src/setuptools/tests
copying setuptools/tests/test_test.py -> build/src/setuptools/tests
copying setuptools/tests/test_upload_docs.py -> build/src/setuptools/tests
copying setuptools/tests/__init__.py -> build/src/setuptools/tests
copying setuptools/command/alias.py -> build/src/setuptools/command
copying setuptools/command/bdist_egg.py -> build/src/setuptools/command
copying setuptools/command/bdist_rpm.py -> build/src/setuptools/command
copying setuptools/command/bdist_wininst.py -> build/src/setuptools/command
copying setuptools/command/build_ext.py -> build/src/setuptools/command
copying setuptools/command/build_py.py -> build/src/setuptools/command
copying setuptools/command/develop.py -> build/src/setuptools/command
copying setuptools/command/easy_install.py -> build/src/setuptools/command
copying setuptools/command/egg_info.py -> build/src/setuptools/command
copying setuptools/command/install.py -> build/src/setuptools/command
copying setuptools/command/install_egg_info.py -> build/src/setuptools/command
copying setuptools/command/install_lib.py -> build/src/setuptools/command
copying setuptools/command/install_scripts.py -> build/src/setuptools/command
copying setuptools/command/register.py -> build/src/setuptools/command
copying setuptools/command/rotate.py -> build/src/setuptools/command
copying setuptools/command/saveopts.py -> build/src/setuptools/command
copying setuptools/command/sdist.py -> build/src/setuptools/command
copying setuptools/command/setopt.py -> build/src/setuptools/command
copying setuptools/command/test.py -> build/src/setuptools/command
copying setuptools/command/upload.py -> build/src/setuptools/command
copying setuptools/command/upload_docs.py -> build/src/setuptools/command
copying setuptools/command/__init__.py -> build/src/setuptools/command
copying setuptools/tests/win_script_wrapper.txt -> build/src/setuptools/tests
copying setuptools/cli-32.exe -> build/src/setuptools
copying setuptools/cli-64.exe -> build/src/setuptools
copying setuptools/cli-arm-32.exe -> build/src/setuptools
copying setuptools/cli.exe -> build/src/setuptools
copying setuptools/gui-32.exe -> build/src/setuptools
copying setuptools/gui-64.exe -> build/src/setuptools
copying setuptools/gui-arm-32.exe -> build/src/setuptools
copying setuptools/gui.exe -> build/src/setuptools
copying setuptools/command/launcher manifest.xml -> build/src/setuptools/command
copying tests/install_test.py -> build/src/tests
copying tests/manual_test.py -> build/src/tests
copying tests/test_distribute_setup.py -> build/src/tests
copying tests/test_pkg_resources.py -> build/src/tests
copying tests/shlib_test/setup.py -> build/src/tests/shlib_test
copying tests/shlib_test/test_hello.py -> build/src/tests/shlib_test
copying tests/shlib_test/hello.c -> build/src/tests/shlib_test
copying tests/shlib_test/hellolib.c -> build/src/tests/shlib_test
copying tests/shlib_test/hello.pyx -> build/src/tests/shlib_test
copying tests/api_tests.txt -> build/src/tests
RefactoringTool: Skipping implicit fixer: buffer
RefactoringTool: Skipping implicit fixer: idioms
RefactoringTool: Skipping implicit fixer: set_literal
RefactoringTool: Skipping implicit fixer: ws_comma
RefactoringTool: Refactored build/src/tests/api_tests.txt
--- build/src/tests/api_tests.txt       (original)
+++ build/src/tests/api_tests.txt       (refactored)
@@ -39,7 +39,7 @@
     >>> dist.py_version == sys.version[:3]
     True

-    >>> print dist.platform
+    >>> print(dist.platform)
     None

 Including various computed attributes::
@@ -199,7 +199,7 @@
 You can ask a WorkingSet to ``find()`` a distribution matching a requirement::

     >>> from pkg_resources import Requirement
-    >>> print ws.find(Requirement.parse("Foo==1.0"))    # no match, return None
+    >>> print(ws.find(Requirement.parse("Foo==1.0")))    # no match, return None
     None

     >>> ws.find(Requirement.parse("Bar==0.9"))  # match, return distribution
@@ -211,7 +211,7 @@
     >>> try:
     ...     ws.find(Requirement.parse("Bar==1.0"))
     ... except VersionConflict:
-    ...     print 'ok'
+    ...     print('ok')
     ok

 You can subscribe a callback function to receive notifications whenever a new
@@ -219,7 +219,7 @@
 once for each existing distribution in the working set, and then is called
 again for new distributions added thereafter::

-    >>> def added(dist): print "Added", dist
+    >>> def added(dist): print("Added", dist)
     >>> ws.subscribe(added)
     Added Bar 0.9
     >>> foo12 = Distribution(project_name="Foo", version="1.2", location="f12")
RefactoringTool: Files that were modified:
RefactoringTool: build/src/tests/api_tests.txt
copying setuptools/tests/indexes/test_links_priority/external.html -> build/src/setuptools/tests/indexes/test_links_priority
copying setuptools/tests/indexes/test_links_priority/simple/foobar/index.html -> build/src/setuptools/tests/indexes/test_links_priority/simple/foobar
copying docs/conf.py -> build/src/docs
copying docs/easy_install.txt -> build/src/docs
copying docs/index.txt -> build/src/docs
copying docs/pkg_resources.txt -> build/src/docs
copying docs/python3.txt -> build/src/docs
copying docs/roadmap.txt -> build/src/docs
copying docs/setuptools.txt -> build/src/docs
copying docs/using.txt -> build/src/docs
copying docs/build/html/_sources/easy_install.txt -> build/src/docs/build/html/_sources
copying docs/build/html/_sources/index.txt -> build/src/docs/build/html/_sources
copying docs/build/html/_sources/pkg_resources.txt -> build/src/docs/build/html/_sources
copying docs/build/html/_sources/python3.txt -> build/src/docs/build/html/_sources
copying docs/build/html/_sources/roadmap.txt -> build/src/docs/build/html/_sources
copying docs/build/html/_sources/setuptools.txt -> build/src/docs/build/html/_sources
copying docs/build/html/_sources/using.txt -> build/src/docs/build/html/_sources
copying docs/_theme/nature/theme.conf -> build/src/docs/_theme/nature
copying docs/_theme/nature/static/pygments.css -> build/src/docs/_theme/nature/static
copying docs/build/html/_static/basic.css -> build/src/docs/build/html/_static
copying docs/build/html/_static/nature.css -> build/src/docs/build/html/_static
copying docs/build/html/_static/pygments.css -> build/src/docs/build/html/_static
copying docs/_theme/nature/static/nature.css_t -> build/src/docs/_theme/nature/static
copying docs/Makefile -> build/src/docs
copying docs/_templates/indexsidebar.html -> build/src/docs/_templates
copying _markerlib/markers.py -> build/src/_markerlib
copying _markerlib/__init__.py -> build/src/_markerlib
copying distribute_setup.py -> build/src
copying easy_install.py -> build/src
copying pkg_resources.py -> build/src
copying release.py -> build/src
copying setup.py -> build/src
copying CHANGES (links).txt -> build/src
copying CHANGES.txt -> build/src
copying CONTRIBUTORS.txt -> build/src
copying DEVGUIDE.txt -> build/src
copying README.txt -> build/src
copying MANIFEST.in -> build/src
copying launcher.c -> build/src
Skipping implicit fixer: buffer
Skipping implicit fixer: idioms
Skipping implicit fixer: set_literal
Skipping implicit fixer: ws_comma
Before install bootstrap.
Scanning installed packages
Setuptools installation detected at /home/noc/ubersystem/env/lib/python3.4/site-packages
Non-egg installation
Could not locate setuptools*.egg-info
Traceback (most recent call last):
  File "/tmp/tmpmroygxt6/distribute-0.6.49/build/src/pkg_resources.py", line 2537, in _dep_map
    return self.__dep_map
  File "/tmp/tmpmroygxt6/distribute-0.6.49/build/src/pkg_resources.py", line 2362, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 232, in <module>
    scripts = scripts,
  File "/usr/local/lib/python3.4/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/tmp/tmpmroygxt6/distribute-0.6.49/build/src/setuptools/dist.py", line 225, in __init__
    _Distribution.__init__(self,attrs)
  File "/usr/local/lib/python3.4/distutils/dist.py", line 280, in __init__
    self.finalize_options()
  File "/tmp/tmpmroygxt6/distribute-0.6.49/build/src/setuptools/dist.py", line 257, in finalize_options
    ep.require(installer=self.fetch_build_egg)
  File "/tmp/tmpmroygxt6/distribute-0.6.49/build/src/pkg_resources.py", line 2100, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer)))
  File "/tmp/tmpmroygxt6/distribute-0.6.49/build/src/pkg_resources.py", line 2310, in requires
    dm = self._dep_map
  File "/tmp/tmpmroygxt6/distribute-0.6.49/build/src/pkg_resources.py", line 2539, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/tmp/tmpmroygxt6/distribute-0.6.49/build/src/pkg_resources.py", line 2572, in _compute_dependencies
    common = frozenset(reqs_for_extra(None))
  File "/tmp/tmpmroygxt6/distribute-0.6.49/build/src/pkg_resources.py", line 2569, in reqs_for_extra
    if req.marker_fn(override={'extra':extra}):
  File "/tmp/tmpmroygxt6/distribute-0.6.49/build/src/_markerlib/markers.py", line 109, in marker_fn
    return eval(compiled_marker, environment)
  File "<environment marker>", line 1, in <module>
NameError: name 'sys_platform' is not defined
Something went wrong during the installation.
See the error message above.
[noc@ubersystem-devel ubersystem]$
```

Additional Relevant Information

| Key  | Value |
| :------------- | :------------- |
| Operating System  | CentOS  |
| Release  | 7.0-1503  |
| Architecture | amd64 |
| Virtual Machine | Yes |
| Python Version | 3.4.3 |
| System Python | No |

Package List (Partial, Hopefully Relevant)
```
postgresql-9.2.10-2.el7_1.x86_64
postgresql-libs-9.2.10-2.el7_1.x86_64
zlib-devel-1.2.7-13.el7.x86_64
git-1.8.3.1-4.el7.x86_64
gcc-4.8.3-9.el7.x86_64
gcc-c++-4.8.3-9.el7.x86_64
1:openssl-devel-1.0.1e-42.el7.4.x86_64
postgresql-devel-9.2.10-2.el7_1.x86_64
postgresql-server-9.2.10-2.el7_1.x86_64
1:openssl-1.0.1e-42.el7.4.x86_64
sqlite-devel-3.7.17-4.el7.x86_64
bzip2-devel-1.0.6-12.el7.x86_64
```

**Comment by binary1230** [comment]
Hey, sorry about that, I have a pull request https://github.com/magfest/ubersystem-deploy/pull/29 to edit the docs.  The manual installation is not a supported method of installation right now, it hasn't been updated in a long time.

The best way to install is to follow the instructions here:
https://github.com/magfest/ubersystem-deploy

Right now we're only supporting Ubuntu 14.04.1 LTS server, but in theory it should work on any *nix with some minor fiddling.

If you're doing a local install to play around, follow the section that says 'Vagrant Install', if you're looking to setup a production server, follow the other section about "Getting started with a real control server" and "Deploying to a target node"

If you run into any snags, feel free to open issues here or also email us at code at magfest dot org

Also, drop us a line, we're always curious who else is using uber.  Good luck!
