### ISSUE TITLE
Viewing a group page without a group leader throws an error

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#1116]
After creating a blank group, trying to view its public page gives the following error:

```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/local/uber/env/lib/python3.4/site-packages/CherryPy-3.6.0-py3.4.egg/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/uber/env/lib/python3.4/site-packages/CherryPy-3.6.0-py3.4.egg/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/uber/env/lib/python3.4/site-packages/CherryPy-3.6.0-py3.4.egg/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 159, in with_timing
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 150, in with_caching
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 174, in with_session
    retval = func(*args, session=session, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 258, in with_restrictions
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 220, in with_rendering
    result = func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/site_sections/preregistration.py", line 51, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/site_sections/preregistration.py", line 283, in group_members
    'charge':  Charge([group, group.leader]),  # Include group leader's kick-in level if not paid-for
  File "/usr/local/uber/plugins/uber/uber/utils.py", line 149, in __init__
    self.targets = [self.to_sessionized(m) for m in listify(targets)]
  File "/usr/local/uber/plugins/uber/uber/utils.py", line 149, in <listcomp>
    self.targets = [self.to_sessionized(m) for m in listify(targets)]
  File "/usr/local/uber/plugins/uber/uber/utils.py", line 162, in to_sessionized
    raise AssertionError('{} is not an attendee or group'.format(m))
AssertionError: None is not an attendee or group```

**Comment by kitsuta** [comment]
Fixed by #1117
