### ISSUE TITLE
FIX BY END OF DAY JULY 23: MAGClassic Unable to pay for group badges

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1253]
Steps to reproduce:

1. Manually Create group of attendees with some number of badges and zero tables
2. override the price to be some custom amount
3. Use the group link to get to the group management page
4. Attempt to use the "pay" link

Result:
Get the following callstack, and the group is not marked as paid.

Traceback (most recent call last): File "/usr/local/uber/plugins/uber/uber/decorators.py", line 117, in charge return func(self, session=session, payment_id=payment_id, stripeToken=stripeToken) File "/usr/local/uber/plugins/uber/uber/site_sections/preregistration.py", line 346, in process_group_payment [attendee] = charge.attendees ValueError: need more than 0 values to unpack

I use this when giving mini-group discounts at otakon, and since that starts tomorrow, It would be nice to have this by tonight

**Comment by EliAndrewC** [comment]
Weird.

This is my gaming night, but that usually wraps up by around 11pm so I can take a stab at this late tonight after everyone leaves.
