### ISSUE TITLE
https://classic.uber.magfest.org/uber/preregistration/check_if_preregistered page fails to actually check

### ISSUE THREAD

**Issue by earl7399** [magfest/ubersystem#1326]
Recommend limiting to once per day, not once per week.  When it works.

Returns:
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 159, in with_timing
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 150, in with_caching
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 174, in with_session
    retval = func(*args, session=session, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 258, in with_restrictions
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 220, in with_rendering
    result = func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/site_sections/preregistration.py", line 47, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/site_sections/preregistration.py", line 109, in check_if_preregistered
    }), model=attendee)
  File "/usr/local/uber/plugins/uber/uber/utils.py", line 163, in send_email
    message=message
  File "/usr/local/uber/plugins/uber/uber/amazon_ses.py", line 101, in sendEmail
    return self._performAction('SendEmail', params)
  File "/usr/local/uber/plugins/uber/uber/amazon_ses.py", line 62, in _performAction
    return self._responseParser.parse(actionName, response.status, response.reason, responseResult)
  File "/usr/local/uber/plugins/uber/uber/amazon_ses.py", line 246, in parse
    self._raiseError(xmlResponse)
  File "/usr/local/uber/plugins/uber/uber/amazon_ses.py", line 237, in _raiseError
    raise AmazonError(errorType, code, message)
uber.amazon_ses.AmazonError: ('Sender', 'MessageRejected', 'Email address is not verified.')

**Comment by kitsuta** [comment]
According to Eli, this is a problem with the address we have configured to send out registration emails. May not be a code issue after all.

**Comment by kitsuta** [comment]
This was a problem with our AWS account, which has been fixed as of now.
