### ISSUE TITLE
MAGClassic Schedule

### ISSUE THREAD

**Issue by StephPrader** [magfest/ubersystem#1347]
Hiya!
Could the schedule be set up like this?
Along the top:
Arcade
Concerts
Console Room
Starship Horizons
LAN
Outdoor Events (if raining TBD) <-- this might get deleted later, I'll let you know, but it's probably good
Panels 1
Panels 2
Panels 3
Registration
Tabletop
Tabletop CCG

Thank you! ^_^;;
Steph

**Comment by kitsuta** [comment]
NOW you tell me. :stuck_out_tongue:

**Comment by StephPrader** [comment]
Well it wasn't imported from the previous year like I'm used to; just
offering corrections. ;p

I've barely played around in this new FANCY uber. I'm buried in
spreadsheets! ^_^ I shall collapse under these COLUMNS! ahhh! I'd rather be
ROWing a boat! Woooooah!

~It's Jon Stewart's last night. I'm grieving in my own way.
Hugs,
Steph

On Thu, Aug 6, 2015 at 8:56 AM, Victoria Earl <notifications@github.com>
wrote:

> NOW you tell me. [image: :stuck_out_tongue:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magfest/ubersystem/issues/1347#issuecomment-128353570>
> .
>



-- 
__
Stephanie Prader
Division Director, Programming
MAGFest
www.magfest.org
703-964-6707

**Comment by StephPrader** [comment]
Didn't see your second question, we need to put some sort of column in there for events. I've got juggling and they don't fit anywhere else. JS Joust too, maybe. They're not in a room, they're in a space. If you've got a better idea than the name Outdoor Events then go for it. ^_^ 
Steph

**Comment by StephPrader** [comment]
So since the schedule is there in uber I thought we could start to put things into it, but then we get this error:
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 174, in with_session
    retval = func(*args, session=session, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 258, in with_restrictions
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 220, in with_rendering
    result = func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/site_sections/schedule.py", line 141, in form
    raise HTTPRedirect('edit#{}', event.start_slot and (event.start_slot - 1))
uber.utils.HTTPRedirect: (['http://classic.uber.magfest.org/uber/schedule/edit#11'], 302)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 159, in with_timing
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 150, in with_caching
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 178, in with_session
    session.commit()
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 790, in commit
    self.transaction.commit()
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2004, in flush
    self._flush(objects)
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2031, in _flush
    self.dispatch.before_flush(self, flush_context, objects)
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/event/attr.py", line 218, in __call__
    fn(*args, **kw)
  File "/usr/local/uber/plugins/uber/uber/models.py", line 1891, in _track_changes
    Tracking.track(action, instance)
  File "/usr/local/uber/plugins/uber/uber/models.py", line 1810, in track
    _insert(instance.session)
  File "/usr/local/uber/plugins/uber/uber/models.py", line 1803, in _insert
    which=repr(instance),
  File "/usr/local/uber/plugins/uber/uber/models.py", line 1500, in __repr__
    return '<{self.attendee.full_name} panelisting {self.event.name}>'.format(self=self)
AttributeError: 'NoneType' object has no attribute 'full_name'
Powered by CherryPy 3.6.0

**Comment by StephPrader** [comment]
This is how the depts are working with the schedule:
1st - Guests put in guest panels
2nd - Panels puts in their picks from the Panel Submission Form
3rd - Panels contacts their panelists to make sure it's cool with their travel plans
4th - I ask the other depts to input their stuff into the schedule

I'm sorry, 11 days ago I wasn't in a rush, but now I am. Help?
Steph

**Comment by kitsuta** [comment]
OK, I will look into this and try to get it fixed tomorrow, if someone else doesn't do it before then.

**Comment by StephPrader** [comment]
Thank you tons Vicki! ^_^
Steph

**Comment by StephPrader** [comment]
Thank you thank you thank youuuuuuuuuuu!
Steph

On Mon, Aug 17, 2015 at 4:11 PM, Victoria Earl <notifications@github.com>
wrote:

> Closed #1347 <https://github.com/magfest/ubersystem/issues/1347> via
> magfest/production-config#33
> <https://github.com/magfest/production-config/pull/33>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/magfest/ubersystem/issues/1347#event-384633745>.
>



-- 
__
Stephanie Prader
Division Director, Programming
MAGFest
www.magfest.org
703-964-6707
