### ISSUE TITLE
error on adding schedule items

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1376]
Steph reports this happens when you try to 'add a panelist' on the add schedule page.

I'll investigate

```python
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
File "/usr/local/uber/plugins/uber/uber/decorators.py", line 174, in with_session
retval = func(args, session=session, *kwargs)
File "/usr/local/uber/plugins/uber/uber/decorators.py", line 258, in with_restrictions
return func(args, *kwargs)
File "/usr/local/uber/plugins/uber/uber/decorators.py", line 220, in with_rendering
result = func(args, *kwargs)
File "/usr/local/uber/plugins/uber/uber/site_sections/schedule.py", line 141, in form
raise HTTPRedirect('edit#{}', event.start_slot and (event.start_slot - 1))
uber.utils.HTTPRedirect: (['http://classic.uber.magfest.org/uber/schedule/edit#11'], 302)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/cprequest.py", line 670, in respond
response.body = self.handler()
File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 217, in __call_
self.body = self.oldhandler(args, *kwargs)
File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/cpdispatch.py", line 61, in __call_
return self.callable(self.args, *self.kwargs)
File "/usr/local/uber/plugins/uber/uber/decorators.py", line 159, in with_timing
return func(args, *kwargs)
File "/usr/local/uber/plugins/uber/uber/decorators.py", line 150, in with_caching
return func(args, *kwargs)
File "/usr/local/uber/plugins/uber/uber/decorators.py", line 178, in with_session
session.commit()
File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 790, in commit
self.transaction.commit()
File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 392, in commit
self.prepare_impl()
File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 372, in prepare_impl
self.session.flush()
File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2004, in flush
self._flush(objects)
File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2031, in _flush
self.dispatch.before_flush(self, flush_context, objects)
File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/event/attr.py", line 218, in __call
fn(args, *kw)
File "/usr/local/uber/plugins/uber/uber/models.py", line 1891, in track_changes
Tracking.track(action, instance)
File "/usr/local/uber/plugins/uber/uber/models.py", line 1810, in track
insert(instance.session)
File "/usr/local/uber/plugins/uber/uber/models.py", line 1803, in _insert
which=repr(instance),
File "/usr/local/uber/plugins/uber/uber/models.py", line 1500, in __repr
return '<{self.attendee.full_name} panelisting {self.event.name}>'.format(self=self)
AttributeError: 'NoneType' object has no attribute 'full_name'
Powered by CherryPy 3.6.0
```

**Comment by binary1230** [comment]
extra note: not sure but I think this might eventually cause the server to crash, which i experienced shortly after trying to repro this on production.  no clue as to why.

proceed with caution.
