### ISSUE TITLE
[2016]500 on attendee list 

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1433]
Went to attendee list, clicked page 1 (https://staging2.uber.magfest.org/uber/registration/index?order=last_first&page=1&search_text=)

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/local/uber/env/lib/python3.4/site-packages/django/template/base.py", line 765, in _resolve_lookup
    current = current[bit]
TypeError: 'Attendee' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 173, in with_timing
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 164, in with_caching
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 188, in with_session
    retval = func(*args, session=session, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 272, in with_restrictions
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 238, in with_rendering
    return render(_get_template_filename(func), result)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 208, in render
    rendered = template.render(Context(data))
  File "/usr/local/uber/env/lib/python3.4/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/usr/local/uber/env/lib/python3.4/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/uber/env/lib/python3.4/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/uber/env/lib/python3.4/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/uber/env/lib/python3.4/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/usr/local/uber/env/lib/python3.4/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/uber/env/lib/python3.4/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/uber/env/lib/python3.4/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/uber/env/lib/python3.4/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/usr/local/uber/env/lib/python3.4/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/usr/local/uber/env/lib/python3.4/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/uber/env/lib/python3.4/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/uber/env/lib/python3.4/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/uber/env/lib/python3.4/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/uber/env/lib/python3.4/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/uber/env/lib/python3.4/site-packages/django/template/defaulttags.py", line 305, in render
    return nodelist.render(context)
  File "/usr/local/uber/env/lib/python3.4/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/usr/local/uber/env/lib/python3.4/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/usr/local/uber/env/lib/python3.4/site-packages/django/template/defaulttags.py", line 196, in render
    nodelist.append(node.render(context))
  File "/usr/local/uber/env/lib/python3.4/site-packages/django/template/debug.py", line 88, in render
    output = self.filter_expression.resolve(context)
  File "/usr/local/uber/env/lib/python3.4/site-packages/django/template/base.py", line 585, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/uber/env/lib/python3.4/site-packages/django/template/base.py", line 735, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/uber/env/lib/python3.4/site-packages/django/template/base.py", line 771, in _resolve_lookup
    current = getattr(current, bit)
  File "/usr/local/uber/plugins/uber/uber/models.py", line 320, in __getattr__
    suffixed = suffix_property.check(self, name)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 52, in _suffix_property_check
    return prop_func(field_name, field_val)
  File "/usr/local/uber/plugins/uber/uber/models.py", line 307, in _label
    return '' if val is None else self.get_field(name).type.choices[int(val)]
KeyError: 50
Powered by CherryPy 3.6.0

**Comment by kitsuta** [comment]
Whoops!

We actually talked about this before - this is the error you get when you have people who kicked in at a level that no longer exists. I've added that level back into our config until we fix the data.
