### ISSUE TITLE
[2016]Panel application error

### ISSUE THREAD

**Issue by nickthenewbie1** [magfest/ubersystem#1441]
Submitted a panel, got this:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 188, in with_session
    retval = func(*args, session=session, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 272, in with_restrictions
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 234, in with_rendering
    result = func(*args, **kwargs)
  File "/usr/local/uber/plugins/panels/panels/site_sections/panel_applications.py", line 33, in index
    raise HTTPRedirect('index?message={}', 'Your panel application has been submitted')
uber.utils.HTTPRedirect: (['http://staging2.uber.magfest.org/uber/panel_applications/index?message=Your%20panel%20application%20has%20been%20submitted'], 302)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: permission denied for relation panel_application

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 173, in with_timing
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 164, in with_caching
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 192, in with_session
    session.commit()
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 790, in commit
    self.transaction.commit()
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2004, in flush
    self._flush(objects)
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2122, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 182, in reraise
    raise value
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2086, in _flush
    flush_context.execute()
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 729, in _emit_insert_statements
    execute(statement, multiparams)
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1332, in _handle_dbapi_exception
    exc_info
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 181, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 442, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) permission denied for relation panel_application
 [SQL: 'INSERT INTO panel_application (id, name, length, description, unavailable, affiliations, past_attendance, presentation, other_presentation, tech_needs, other_tech_needs) VALUES (%(id)s, %(name)s, %(length)s, %(description)s, %(unavailable)s, %(affiliations)s, %(past_attendance)s, %(presentation)s, %(other_presentation)s, %(tech_needs)s, %(other_tech_needs)s)'] [parameters: {'length': 'Expected Panel Length:', 'tech_needs': '198351673', 'presentation': 25099970, 'other_tech_needs': '', 'other_presentation': '', 'past_attendance': 'Where and how many people attended?', 'affiliations': 'What are they?', 'name': 'Panel Name', 'description': 'Panel Description', 'id': UUID('edb4db7c-4a92-40c7-b94e-e929d8edeffc'), 'unavailable': 'When are you unavailable?.'}]
Powered by CherryPy 3.6.0

**Comment by kitsuta** [comment]
Hm, looks like the sqlalchemy user lacks permissions to alter these tables. Let me see what I can do.

**Comment by kitsuta** [comment]
OK, the table was created incorrectly on the server. I've fixed it and verified it as working.
