### ISSUE TITLE
callstack error - NontType in has_email_address

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1503]
was reviewing the logs, saw this from 10:03am this morning.

this may be something related to Eli testing stuff and has already been fixed, but, just in case, here it is:

Sep 11 10:03:38 rams1 2015-09-11 10:03:38,748 [ERROR] cherrypy.error.140061867551544: [11/Sep/2015:10:03:38] HTTP Traceback (most recent call last):#012  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond#012    response.body = self.handler()#012  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 217, in __call__#012    self.body = self.oldhandler(*args, **kwargs)#012  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__#012    return self.callable(*self.args, **self.kwargs)#012  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 179, in with_timing#012    return func(*args, **kwargs)#012  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 170, in with_caching#012    return func(*args, **kwargs)#012  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 194, in with_session#012    retval = func(*args, session=session, **kwargs)#012  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 278, in with_restrictions#012    return func(*args, **kwargs)#012  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 240, in with_rendering#012    result = func(*args, **kwargs)#012  File "/usr/local/uber/plugins/uber/uber/site_sections/accounts.py", line 34, in update#012    message = check(account)#012  File "/usr/local/uber/plugins/uber/uber/utils.py", line 74, in check#012    message = validator(model)#012  File "/usr/local/uber/plugins/uber/uber/model_checks.py", line 32, in has_email_address#012    if session.query(Attendee).filter_by(id=account.attendee_id).first().email == '':#012AttributeError: 'NoneType' object has no attribute 'email'

**Comment by kitsuta** [comment]
This is the system being unable to find an admin account in the session.
