### ISSUE TITLE
need better error message when using invalid attendee UUID

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1564]
Example:
https://prime.uber.magfest.org/uber/registration/form?id=ffffffff-ffff-ffff-ffff-ffffffffffff

Expected:
error message that says "This attendee does not exist, invalid UUID"

Actual:
Slightly obscure non-obvious traceback:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

```python
Traceback (most recent call last):
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 179, in with_timing
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 170, in with_caching
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 194, in with_session
    retval = func(*args, session=session, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 278, in with_restrictions
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 240, in with_rendering
    result = func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 13, in with_check
    sa.Tracking.track_pageview(cherrypy.request.path_info, cherrypy.request.query_string)
  File "/usr/local/uber/plugins/uber/uber/models.py", line 1730, in track_pageview
    Tracking.track(c.PAGE_VIEWED, attendee)
  File "/usr/local/uber/plugins/uber/uber/models.py", line 1691, in track
    data = 'id={}'.format(instance.id)
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by binary1230** [comment]
found this when clicking on an attendee added to the watchlist that we later deleted or something. bug happens on any valid hexstring that doesn't map to a real user.
