### ISSUE TITLE
signups report doesn't handle 'All' case

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1568]
visit https://prime.uber.magfest.org/uber/jobs/signups?location=All
BOOM

```
Traceback (most recent call last):
  File "/usr/local/uber/plugins/uber/uber/models.py", line 111, in process_bind_param
    assert self.allow_unspecified or int(value) in self.choices
ValueError: invalid literal for int() with base 10: 'All'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1073, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 600, in _init_compiled
    for key in compiled_params
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 600, in <genexpr>
    for key in compiled_params
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/sql/type_api.py", line 935, in process
    return process_param(value, dialect)
  File "/usr/local/uber/plugins/uber/uber/models.py", line 113, in process_bind_param
    raise ValueError('{!r} not a valid option out of {}'.format(value, self.choices))
ValueError: 'All' not a valid option out of {201806081: 'Jam Space', 13980098: 'Tabletop', 125461766: 'Indie Games', 39626696: 'Events', 162026633: 'LARP', 121371850: 'Load-In', 41143055: 'Concert Security', 99437969: 'LAN', 162178642: 'Starship Horizons', 44461843: 'Dorsai', 264984698: 'Treasury', 252033110: 'Tech Ops', 145272663: 'Tea Room', 45526872: 'Reg Managers', 67819226: 'Games on Film', 266491407: 'Charity', 182365021: 'Challenges', 29995679: 'Staffing Ops', 136514017: 'Public Safety', 248958555: 'Rock Island', 195687140: 'Dispatch', 163373830: 'Concert', 181632678: 'Security', 157456935: 'Chipspace', 59983785: 'Arcade', 85962282: 'Tabletop (CCG)', 134279079: 'Marketplace', 168807599: 'Consoles', 87044527: 'Artemis', 96537235: 'Rescuers', 58114932: 'LAN Events', 80341158: 'Staff Support', 216073079: 'MEDIATRON!', 210159096: 'Staff Suite', 140221626: 'Jam Clinic', 177161930: 'Regdesk', 251700478: 'Merchandise', 84837183: 'Fest Ops'}
```

probably just need to special-case location='All' in signups() to be from this:

```
        if location is None:
            location = cherrypy.session.get('prev_location') or c.JOB_LOCATION_OPTS[0][0]
```

to this

```
        if location is None or location == 'All':
            location = cherrypy.session.get('prev_location') or c.JOB_LOCATION_OPTS[0][0]
```

or, rewrite jobs.py signups() to deal with showing 'All' locations

**Comment by RobRuana** [comment]
Fixed during the big departments refactor.
