### ISSUE TITLE
Semi-unique constraint on badge numbers

### ISSUE THREAD

**Issue by EliAndrewC** [magfest/ubersystem#1637]
When I originally implemented the badge number column, I didn't add a unique constraint because we don't assign a lot of badge numbers until people check in, which means we intentionally have a lot of repeated values.

What I didn't know is that in Postgres it actually is possible to say "this column is unique and no two values should ever be the same EXCEPT for null, which can appear in as many rows as you want".

We should probably do that, for data integrity reasons.  This would ALSO remove "0" as a special case badge number, which is good because that makes a lot of our data integrity checks harder.

**Comment by kitsuta** [comment]
Hey, I made an attempt at this for #1901, but it broke when the system started to try to shift badges - it was claiming the the UNIQUE constraint was being violated, presumably because it was trying to insert badge 3000 before moving badge 3000 to 3001.

**Comment by EliAndrewC** [comment]
Oh yeah, I ran into this same problem on a project at work.  There's some way to say "don't try to enforce this unique constraint until the very end of the transation" in Postgres, which is known as a "deferrable constraint".  This is something we can set through SQLAlchemy, and the only slightly-tricky thing is setting it in a way that doesn't mess up our unit tests (since SQLite doesn't support deferrable constraints and we use SQLite for our unit tests).

I'm off work today so I won't be able to look up how we did this until Monday, but when I get back to work I look up how we did this.  In theory we could figure it out from scratch using the SQLAlchemy docs, but in practice the SQLAlchemy docs are pretty bad for figuring this kind of stuff out.

**Comment by kitsuta** [comment]
Hm, besides breaking unit tests, this doesn't seem to work at all. I tried adding a deferrable unique constraint on the badge_num column, like so:
```
    __table_args__ = (
        UniqueConstraint('badge_num', deferrable=True),
    )
```

And I still get a unique constraint violated error, like the one below:
```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/home/vagrant/uber/sideboard/plugins/uber/uber/decorators.py", line 196, in with_session
    retval = func(*args, session=session, **kwargs)
  File "/home/vagrant/uber/sideboard/plugins/uber/uber/decorators.py", line 280, in with_restrictions
    return func(*args, **kwargs)
  File "/home/vagrant/uber/sideboard/plugins/uber/uber/decorators.py", line 242, in with_rendering
    result = func(*args, **kwargs)
  File "/home/vagrant/uber/sideboard/plugins/uber/uber/site_sections/registration.py", line 150, in change_badge
    raise HTTPRedirect('form?id={}&message={}', attendee.id, message or '')
uber.utils.HTTPRedirect: (['http://localhost/uber/registration/form?id=b76b375f-4ae6-424a-9092-0212e55e6e71&message=Badge%20updated'], 302)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1116, in _execute_context
    context)
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 439, in do_executemany
    cursor.executemany(statement, parameters)
psycopg2.IntegrityError: duplicate key value violates unique constraint "attendee_badge_num_key"
DETAIL:  Key (badge_num)=(153) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/vagrant/uber/sideboard/plugins/uber/uber/decorators.py", line 181, in with_timing
    return func(*args, **kwargs)
  File "/home/vagrant/uber/sideboard/plugins/uber/uber/decorators.py", line 172, in with_caching
    return func(*args, **kwargs)
  File "/home/vagrant/uber/sideboard/plugins/uber/uber/decorators.py", line 200, in with_session
    session.commit()
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 790, in commit
    self.transaction.commit()
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2004, in flush
    self._flush(objects)
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2122, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 182, in reraise
    raise value
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2086, in _flush
    flush_context.execute()
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 170, in save_obj
    mapper, table, update)
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 673, in _emit_update_statements
    execute(statement, multiparams)
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1332, in _handle_dbapi_exception
    exc_info
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 181, in reraise
    raise value.with_traceback(tb)
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1116, in _execute_context
    context)
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 439, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "attendee_badge_num_key"
DETAIL:  Key (badge_num)=(153) already exists.
 [SQL: 'UPDATE attendee SET badge_num=%(badge_num)s WHERE attendee.id = %(attendee_id)s'] [parameters: ({'attendee_id': UUID('5ed2f565-08d3-4f1a-9982-d58a3a148d6b'), 'badge_num': 153}, {'attendee_id': UUID('b76b375f-4ae6-424a-9092-0212e55e6e71'), 'badge_num': 152})]
Powered by CherryPy 3.6.0
```

**Comment by EliAndrewC** [comment]
Weird.  I guess I'll have to double check how we did this at work on Monday and then report back.

**Comment by EliAndrewC** [comment]
Here's what we did at my job when this came up:

```python
IS_POSTGRES = True if 'postgres' in SQLALCHEMY_URL else None

class Foo(ModelBase):
    label = Column(Unicode)

    if IS_POSTGRES:
        __table_args__ = (
            UniqueConstraint('label', name='label_uc', deferrable=True, initially='DEFERRED'),
        )
```

Now that I look at this code, I remember that when we tried passing the constraint information directly to the ``Column`` definition it didn't work, which is why we needed to define a ``UniqueConstraint`` in the table args.

**Comment by kitsuta** [comment]
Huh. Initialliy='DEFERRED'? That's a new one to me. I'll try it with that
and the IS_POSTGRES flag.
