### ISSUE TITLE
MAGStock Schedule not working

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1811]
https://magstock6.uber.magfest.org/uber/schedule/

Traceback (most recent call last):
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cperror.py", line 411, in __call__
    raise self
cherrypy._cperror.NotFound: (404, "The path '/uber/schedule/' was not found.")

**Comment by binary1230** [comment]
it's because the schedule is now part of the panels plugin and magstock uber doesn't have it enabled yet because of some code issues

**Comment by binary1230** [comment]
initial schedule is in there so this is fixed for now, we will need to add columns for 'event_locations'
