### ISSUE TITLE
Lab Registration Error

### ISSUE THREAD

**Issue by bds002** [magfest/ubersystem#1840]
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 179, in with_timing
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 170, in with_caching
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 194, in with_session
    retval = func(*args, session=session, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 278, in with_restrictions
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 240, in with_rendering
    result = func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/site_sections/preregistration.py", line 23, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 27, in with_check
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/site_sections/preregistration.py", line 126, in form
    message = check(attendee, prereg=True)
  File "/usr/local/uber/plugins/uber/uber/utils.py", line 75, in check
    message = validator(model)
  File "/usr/local/uber/plugins/uber/uber/model_checks.py", line 106, in total_cost_over_paid
    if attendee.total_cost < attendee.amount_paid:
  File "/usr/local/uber/plugins/uber/uber/models.py", line 1140, in total_cost
    return self.default_cost + self.amount_extra
  File "/usr/local/uber/plugins/uber/uber/models.py", line 201, in default_cost
    return max(0, sum([getattr(self, name) for name in self.cost_property_names], 0))
  File "/usr/local/uber/plugins/uber/uber/models.py", line 201, in <listcomp>
    return max(0, sum([getattr(self, name) for name in self.cost_property_names], 0))
  File "/usr/local/uber/plugins/uber/uber/models.py", line 1118, in badge_cost
    elif self.is_presold_oneday:
  File "/usr/local/uber/plugins/uber/uber/models.py", line 1168, in is_presold_oneday
    return self.badge_type_label in c.DAYS_OF_WEEK
  File "/usr/local/uber/plugins/uber/uber/models.py", line 312, in __getattr__
    suffixed = suffix_property.check(self, name)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 52, in _suffix_property_check
    return prop_func(field_name, field_val)
  File "/usr/local/uber/plugins/uber/uber/models.py", line 299, in _label
    return '' if val is None else self.get_field(name).type.choices[int(val)]
KeyError: 1

**Comment by bds002** [comment]
Error when I tried to register 100 people on group with Shirt and Supporter add on.
