### ISSUE TITLE
Going to Signups view on Jobs for concert tent produces a 500 error

### ISSUE THREAD

**Issue by pelololoquin** [magfest/ubersystem#1860]
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 179, in with_timing
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 170, in with_caching
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 194, in with_session
    retval = func(*args, session=session, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 278, in with_restrictions
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 240, in with_rendering
    result = func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/site_sections/jobs.py", line 71, in signups
    'checklist': location and session.checklist_status('postcon_hours', location)
  File "/usr/local/uber/plugins/uber/uber/models.py", line 456, in checklist_status
    raise ValueError("Can't access dept checklist INI settings for section '{}', check your INI file".format(slug))
ValueError: Can't access dept checklist INI settings for section 'postcon_hours', check your INI file
Powered by CherryPy 3.6.0

**Comment by binary1230** [comment]
will check in  afew

**Comment by binary1230** [comment]
it's likely because we don't have a postcon_hours section, we'll prob have to remove from the INI.  weird
