### ISSUE TITLE
summary page is broken

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1933]
don't have time to investigate right now, error is:

```
Traceback Detected
2016-08-08 18:55:47,885 [ERROR] uber.server: Exception encountered
   Request: GET /uber/summary/ HTTP/1.0
   Request Params:

   Session Params:
   dict_items([('csrf_token', '[secret-removed]'), ('unpaid_preregs', OrderedDict()), ('account_id', '[secret-removed]')])
   Request Headers:
     Remote-Addr: 127.0.0.1
     USER-AGENT: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
     ACCEPT-LANGUAGE: en-US,en;q=0.8
     ACCEPT-ENCODING: gzip, deflate, sdch, br
     ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
     DNT: 1
     CONNECTION: close
     UPGRADE-INSECURE-REQUESTS: 1
     REFERER: https://labs.uber.magfest.org/uber/jobs/
     HOST: labs.uber.magfest.org
   Traceback (most recent call last):
     File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
       response.body = self.handler()
     File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
       self.body = self.oldhandler(*args, **kwargs)
     File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
       return self.callable(*self.args, **self.kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 196, in with_timing
       return func(*args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 187, in with_caching
       return func(*args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 211, in with_session
       retval = func(*args, session=session, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 324, in with_restrictions
       return func(*args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 273, in with_rendering
       result = func(*args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/site_sections/summary.py", line 31, in index
       counts['ages'][a.age_group_label] += 1
     File "/usr/local/uber/plugins/uber/uber/models.py", line 333, in __getattr__
       raise AttributeError(self.__class__.__name__ + '.' + name)
   AttributeError: Attendee.age_group_label
```

you can repro simply by visiting on maglabs uber /uber/summary

**Comment by kitsuta** [comment]
Oof, this is probably because we changed the age group configuration. There are likely a few dozen attendees with an age group INT that no longer exists. Let me see if I can just fix the data manually.

**Comment by kitsuta** [comment]
Oh wait, I don't actually have an account for MAGLabs.

Basically all one would need to do is find everyone who would have been "under 7" and re-save them so their age group is changed to "under 6" or "under 13," respectively. To be thorough, I would go ahead and hit everyone born in the year 2007 or later.
