### ISSUE TITLE
exceptions raised in Config __getattr__() don't show original error

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#1942]
insert the following code into config.py in the Config() class:

```
    @property
    def OUTER_LEGIT_PROPERTY(self):
        return c.NONEXISTENT_PROPERTY
```

in a python console run the following command:

```c.OUTER_LEGIT_PROPERTY```

expected: you get an error message with at last some mention about how c.NONEXISTENT_PROPERTY wasn't found in the Config() class

actual: you get a slightly more confusing error message about ONLY the property 'OUTER_LEGIT_PROPERTY' which doesn't mention the true problem, that c.NONEXISTENT_PROPERTY doesn't exist:

```python
>>> c.OUTER_LEGIT_PROPERTY
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/vagrant/uber/sideboard/plugins/uber/uber/config.py", line 295, in __getattr__
    raise AttributeError('no such attribute {}'.format(name))
AttributeError: no such attribute OUTER_LEGIT_PROPERTY
```

----

This seems to be an issue with ```def __getattr__(self, name):``` in config.py, specifically,
```raise AttributeError('no such attribute {}'.format(name))```

what happens in this case is we raise an AttributeError() for c.NONEXISTENT_PROPERTY (which is good), but then we raise another AttributeError() for c.OUTER_LEGIT_PROPERTY

I don't have time to look at it today but it would be good if the raise detects that it's already handling an exception and then chains onto it, so the combined exception would say something about 'c.OUTER_LEGIT_PROPERTY caused an exception, inner exception is "can't find c.NONEXISTENT_PROPERTY"'

**Comment by binary1230** [comment]
just ran into this in another spot, 
def __getattr__(self, name): in models.py in MagModel class:

```raise AttributeError(self.__class__.__name__ + '.' + name)```

**Comment by RobRuana** [comment]
Some good discussion over here in this duplicate issue #2842
