### ISSUE TITLE
add error message to prereg confirm page

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#2084]
in uber/models.py, this line:

```
assert not {k for k in params if k not in allowed} or cherrypy.request.method == 'POST', 'POST required'
```

causes a nasty looking error message for end users.  it's meant to prevent tampering but we're seeing this hit in the alterting system probably with some attendee refreshing the page.  would be better to just redirect to the main prereg form page with a message like 'Sorry, something went wrong accessing that page, please try again'.  

Then 1) the end user gets a nicer looking message and 2) we  won't get pinged on our alerting system

**Comment by binary1230** [comment]
traceback:

```
2016-10-11 16:01:44,479 [ERROR] uber.server: Exception encountered
   Request: GET /uber/preregistration/confirm?id%3D[REMOVED] HTTP/1.0
   Current admin user is: [non-admin user]
   Request Params:
     id=[REMOVED]: 
   Session Params:
   dict_items([])
   Request Headers:
     Remote-Addr: 127.0.0.1
     USER-AGENT: AHC/2.0
     CONNECTION: close
     ACCEPT: */*
     X-FORWARDED-PROTO: https
     X-FORWARDED-HOST: super2017.uber.magfest.org
     HOST: super2017.uber.magfest.org
   Traceback (most recent call last):
     File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
       response.body = self.handler()
     File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
       self.body = self.oldhandler(*args, **kwargs)
     File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
       return self.callable(*self.args, **self.kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 224, in with_timing
       return func(*args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 215, in with_caching
       return func(*args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 239, in with_session
       retval = func(*args, session=session, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 355, in with_restrictions
       return func(*args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 304, in with_rendering
       result = func(*args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/site_sections/preregistration.py", line 23, in wrapped
       return func(self, *args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/site_sections/preregistration.py", line 429, in confirm
       attendee = session.attendee(params, restricted=True)
     File "/usr/local/uber/plugins/uber/uber/models.py", line 2056, in with_validity_check
       attendee = orig_getter(self, *args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/models.py", line 1951, in getter
       assert not {k for k in params if k not in allowed} or cherrypy.request.method == 'POST', 'POST required'
   AssertionError: POST required 
```
