### ISSUE TITLE
/uber/summary/food_restrictions report is broken

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#2136]
```python
Traceback (most recent call last):
  File "/usr/local/uber/plugins/uber/uber/models.py", line 1572, in __getattr__
    return super(FoodRestrictions, self).__getattr__(name)
  File "/usr/local/uber/plugins/uber/uber/models.py", line 336, in __getattr__
    raise AttributeError(self.__class__.__name__ + '.' + name)
AttributeError: FoodRestrictions.GLUTEN

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 224, in with_timing
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 215, in with_caching
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 239, in with_session
    retval = func(*args, session=session, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 355, in with_restrictions
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 304, in with_rendering
    result = func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/site_sections/summary.py", line 103, in food_restrictions
    for category in c.FOOD_RESTRICTION_VARS
  File "/usr/local/uber/plugins/uber/uber/site_sections/summary.py", line 103, in <dictcomp>
    for category in c.FOOD_RESTRICTION_VARS
  File "/usr/local/uber/plugins/uber/uber/site_sections/summary.py", line 102, in <listcomp>
    c.FOOD_RESTRICTIONS[getattr(c, category)]: len([fr for fr in all_fr if getattr(fr, category)])
  File "/usr/local/uber/plugins/uber/uber/models.py", line 1577, in __getattr__
    elif restriction == c.VEGETARIAN and c.VEGAN in self.standard_ints:
  File "/usr/local/uber/plugins/uber/uber/config.py", line 336, in __getattr__
    raise AttributeError('no such attribute {}'.format(name))
AttributeError: no such attribute VEGETARIAN
```

**Comment by migetman9** [comment]
Okay so this error is because c.VEGETARIAN was either forgotten from the config, or left in the code when we stopped using it. 
<img width="485" alt="screen shot 2016-11-23 at 11 15 05 am" src="https://cloud.githubusercontent.com/assets/6538753/20575442/1f5a9ca0-b16e-11e6-9a2a-1b84dd1d4a92.png">

**Comment by migetman9** [comment]
When I think about it, why would we get rid of vegetarian as an option? I am bad with food. We should re-add to the config. @binary1230 can do?

**Comment by binary1230** [comment]
I remember there was an explicit reason it was removed, maybe it wasn't an explicit option in the staff suite anymore.  might have to dig around in the code history for why

**Comment by bds002** [comment]
The display / check box options for the Food_restrictions form was heavily edited from past years.
Current: https://super2017.uber.magfest.org/uber/signups/food_restrictions
At one point Staff Suite had separate Vegetarian and Vegan options. Since All Vegan is also Vegetarian they combined some options on the form.

**Comment by migetman9** [comment]
I will remove the old leftover code then

**Comment by kitsuta** [comment]
Fixed by https://github.com/magfest/ubersystem/pull/2153. I can't believe I missed this when removing these options. :\
