### ISSUE TITLE
badge subject line error

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#2164]
need more research, saw this going across the logs:

```
2016-11-26 00:38:04,588 [ERROR] uber.decorators: encountered exception, forcing continuation anyway
   Traceback (most recent call last):
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 246, in with_session
       retval = func(*args, session=session, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 362, in with_restrictions
       return func(*args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 311, in with_rendering
       result = func(*args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 85, in protected
       return func(*args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/site_sections/emails.py", line 71, in approve
       raise HTTPRedirect('pending?message={}', 'Email approved and will be sent out shortly')
   uber.utils.HTTPRedirect: (['https://super2017.uber.magfest.org/uber/emails/pending?message=Email%20approved%20and%20will%20be%20sent%20out%20shortly'], 302)
   
   During handling of the above exception, another exception occurred:
   
   Traceback (most recent call last):
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 13, in swallow_exception
       return func(*args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/models.py", line 2002, in _track_changes
       Tracking.track(action, instance)
     File "/usr/local/uber/plugins/uber/uber/models.py", line 1871, in track
       vals = {attr: cls.repr(column, getattr(instance, attr)) for attr, column in instance.__table__.columns.items()}
     File "/usr/local/uber/plugins/uber/uber/models.py", line 1871, in <dictcomp>
       vals = {attr: cls.repr(column, getattr(instance, attr)) for attr, column in instance.__table__.columns.items()}
     File "/usr/local/uber/plugins/uber/uber/models.py", line 336, in __getattr__
       raise AttributeError(self.__class__.__name__ + '.' + name)
   AttributeError: ApprovedEmail.subject 
```

This could be related to some of the recent panel emails changes, @EliAndrewC ? Haven't seen this particular error before today.

**Comment by EliAndrewC** [comment]
Ahh, I see what happened.  This is a fairly harmless error that we can ignore for now.  I'll explain what's going on below.

By default, SQLAlchemy uses column property names as column names.  For example, when you say

```
class Foo(MagModel):
    bar = Column(UnicodeText)
```

then SQLAlchemy uses ``bar`` as the name of the column.  However, that's not the only way to do it; you can specify the column name yourself and make it different from the column property name, e.g.

```
class Foo(MagModel):
    bar = Column('actual_column_name', UnicodeText)
```

We have some ``Tracking`` code that apparently doesn't work properly if the column name is different from the property name.  Which has never happened before now, but I wanted to rename ``subject`` to ``ident`` without doing a database migration so I went ahead and just did that.

The end result is that this line
https://github.com/magfest/ubersystem/blob/master/uber/models.py#L1871
```
vals = {attr: cls.repr(column, getattr(instance, attr)) for attr, column in instance.__table__.columns.items()}
```
doesn't work because the column name is ``subject`` but the attribute name is ``ident``.

This exception is caught by a try/except, so the only result is that when Brent or whoever pressed the Approve button on that hotel room email earlier tonight, the action worked but we didn't get a row inserted into the ``Tracking`` table for that insert.

In the short run we can do a db migration if we want to actually rename ``subject`` to ``ident``.  In the medium/long run we can update the ``Tracking.track`` function to properly handle this edge case where columns are named differently than their properties.  In the immediate term we can just ignore this because there's no operational impact.
