### ISSUE TITLE
MAGSTOCK PRODUCTION ERROR

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2416]
```
Traceback Detected
Traceback Detected

Location: magstock7.uber.magfest.org    Time: 2017-03-31T20:45:01.460Z
2017-03-31 16:44:53,994 [ERROR] uber.server: 
   Exception encountered
   Request: GET /uber/preregistration/transfer_badge?id=XXX HTTP/1.0
   Traceback (most recent call last):
     File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
       response.body = self.handler()
     File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
       self.body = self.oldhandler(*args, **kwargs)
     File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
       return self.callable(*self.args, **self.kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 238, in with_timing
       return func(*args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 229, in with_caching
       return func(*args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 253, in with_session
       retval = func(*args, session=session, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 381, in with_restrictions
       return func(*args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 347, in with_rendering
       return render(_get_template_filename(func), result)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 274, in render
       rendered = template.render(data)
     File "/usr/local/uber/env/lib/python3.4/site-packages/jinja2/environment.py", line 1008, in render
       return self.environment.handle_exception(exc_info, True)
     File "/usr/local/uber/env/lib/python3.4/site-packages/jinja2/environment.py", line 780, in handle_exception
       reraise(exc_type, exc_value, tb)
     File "/usr/local/uber/env/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
       raise value.with_traceback(tb)
     File "/usr/local/uber/plugins/uber/uber/templates/preregistration/transfer_badge.html", line 1, in top-level template code
       {% extends "./preregistration/preregbase.html" %}
     File "/usr/local/uber/plugins/uber/uber/templates/preregistration/preregbase.html", line 1, in top-level template code
       {% extends "base.html" %}
     File "/usr/local/uber/plugins/uber/uber/templates/base.html", line 226, in top-level template code
       {% block content %}{% endblock %}
     File "/usr/local/uber/plugins/uber/uber/templates/preregistration/transfer_badge.html", line 22, in block "content"
       {% include "regform.html" %}
     File "/usr/local/uber/plugins/uber/uber/templates/regform.html", line 177, in top-level template code
       data: {{ affiliates|jsonize }},
     File "/usr/local/uber/plugins/uber/uber/custom_tags.py", line 95, in jsonize
       return safe_string('{}' if x is None else html.escape(json.dumps(x, cls=serializer), quote=False))
     File "/usr/lib/python3.4/json/__init__.py", line 237, in dumps
       **kw).encode(obj)
     File "/usr/lib/python3.4/json/encoder.py", line 192, in encode
       chunks = self.iterencode(o, _one_shot=True)
     File "/usr/lib/python3.4/json/encoder.py", line 250, in iterencode
       return _iterencode(o, 0)
     File "/usr/local/uber/sideboard/lib/_utils.py", line 45, in default
       raise json.JSONEncoder.default(self, o)
     File "/usr/lib/python3.4/json/encoder.py", line 173, in default
       raise TypeError(repr(o) + " is not JSON serializable")
   TypeError: Undefined is not JSON serializable
```

**Comment by binary1230** [comment]
looks like: ```{{ affiliates|jsonize }}```

I wonder if related to #1632

**Comment by binary1230** [comment]
```"/usr/local/uber/plugins/uber/uber/templates/preregistration/transfer_badge.html", line 22, in block "content"
       {% include "regform.html" %}
     File "/usr/local/uber/plugins/uber/uber/templates/regform.html", line 177, in top-level template code
       data: {{ affiliates|jsonize }},
     File "/usr/local/uber/plugins/uber/uber/custom_tags.py", line 95, in jsonize
       return safe_string('{}' if x is None else html.escape(json.dumps(x, cls=serializer), quote=False))
     File "/usr/lib/python3.4/json/__init__.py", line 237, in dumps
       **kw).encode(obj)
     File "/usr/lib/python3.4/json/encoder.py", line 192, in encode
       chunks = self.iterencode(o, _one_shot=True)
     File "/usr/lib/python3.4/json/encoder.py", line 250, in iterencode
       return _iterencode(o, 0)
     File "/usr/local/uber/sideboard/lib/_utils.py", line 45, in default
       raise json.JSONEncoder.default(self, o)
     File "/usr/lib/python3.4/json/encoder.py", line 173, in default
       raise TypeError(repr(o) + " is not JSON serializable")
   TypeError: Undefined is not JSON serializable```
