### ISSUE TITLE
ERROR IN PRODUCTION WEST

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2463]
```
 Traceback (most recent call last):
     File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
       response.body = self.handler()
     File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
       self.body = self.oldhandler(*args, **kwargs)
     File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
       return self.callable(*self.args, **self.kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 238, in with_timing
       return func(*args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 229, in with_caching
       return func(*args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 253, in with_session
       retval = func(*args, session=session, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 381, in with_restrictions
       return func(*args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 347, in with_rendering
       return render(_get_template_filename(func), result)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 274, in render
       rendered = template.render(data)
     File "/usr/local/uber/env/lib/python3.4/site-packages/jinja2/environment.py", line 1008, in render
       return self.environment.handle_exception(exc_info, True)
     File "/usr/local/uber/env/lib/python3.4/site-packages/jinja2/environment.py", line 780, in handle_exception
       reraise(exc_type, exc_value, tb)
     File "/usr/local/uber/env/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
       raise value.with_traceback(tb)
     File "/usr/local/uber/plugins/panels/panels/templates/panel_applications/index.html", line 1, in top-level template code
       {% extends "preregistration/preregbase.html" %}
     File "/usr/local/uber/plugins/uber/uber/templates/preregistration/preregbase.html", line 1, in top-level template code
       {% extends "base.html" %}
     File "/usr/local/uber/plugins/uber/uber/templates/base.html", line 229, in top-level template code
       {% block content %}{% endblock %}
     File "/usr/local/uber/plugins/panels/panels/templates/panel_applications/index.html", line 240, in block "content"
       <td><b>Other Panelist #{{ forloop.counter }}</b></td>
     File "/usr/local/uber/env/lib/python3.4/site-packages/jinja2/environment.py", line 430, in getattr
       return getattr(obj, attribute)
   jinja2.exceptions.UndefinedError: 'forloop' is undefined
```

**Comment by RobRuana** [comment]
Fixed by:
* https://github.com/magfest/panels/pull/78
* https://github.com/magfest/uber_analytics/pull/15
