### ISSUE TITLE
500 error when changing a badge from staff to attendee

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#2472]
When trying to change staff badge 79 to an attendee, this error occurs:
```
Traceback (most recent call last):
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 688, in _commit_impl
       self.engine.dialect.do_commit(self.connection)
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 415, in do_commit
       dbapi_connection.commit()
   psycopg2.IntegrityError: duplicate key value violates unique constraint "attendee_badge_num_key"
   DETAIL:  Key (badge_num)=(78) already exists.
   
   
   The above exception was the direct cause of the following exception:
   
   Traceback (most recent call last):
     File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
       response.body = self.handler()
     File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
       self.body = self.oldhandler(*args, **kwargs)
     File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
       return self.callable(*self.args, **self.kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 238, in with_timing
       return func(*args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 229, in with_caching
       return func(*args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 257, in with_session
       session.commit()
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 790, in commit
       self.transaction.commit()
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 396, in commit
       t[1].commit()
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1560, in commit
       self._do_commit()
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1591, in _do_commit
       self.connection._commit_impl()
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 690, in _commit_impl
       self._handle_dbapi_exception(e, None, None, None, None)
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1332, in _handle_dbapi_exception
       exc_info
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 188, in raise_from_cause
       reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 181, in reraise
       raise value.with_traceback(tb)
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 688, in _commit_impl
       self.engine.dialect.do_commit(self.connection)
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 415, in do_commit
       dbapi_connection.commit()
   sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "attendee_badge_num_key"
   DETAIL:  Key (badge_num)=(78) already exists.
```

**Comment by kitsuta** [comment]
Based on the badge ranges, this looks like a problem caused by the badge shifting code. Definitely new for this year.

**Comment by RobRuana** [comment]
Is this new as in, from the code we just pushed?

**Comment by kitsuta** [comment]
Don't know. :\
