### ISSUE TITLE
ERROR in production west

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2518]
```
2017-06-01 22:25:40,386 [ERROR] uber.decorators: Exception raised, but we're going to ignore it and continue.
   Traceback (most recent call last):
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 254, in with_session
       retval = func(*args, session=session, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 375, in with_restrictions
       return func(*args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 315, in with_rendering
       result = func(*args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 30, in with_check
       return func(*args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/site_sections/groups.py", line 58, in form
       raise HTTPRedirect('form?id={}&message={}', group.id, 'Group info uploaded')
   uber.utils.HTTPRedirect: (['https://west2017.uber.magfest.org/uber/groups/form?id=XXX&message=Group%20info%20uploaded'], 302)
   
   During handling of the above exception, another exception occurred:
   
   Traceback (most recent call last):
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 14, in swallow_exception
       return func(*args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/models.py", line 2137, in _presave_adjustments
       model.presave_adjustments()
     File "/usr/local/uber/plugins/uber/uber/models.py", line 167, in presave_adjustments
       self._invoke_adjustment_callbacks('presave_adjustment')
     File "/usr/local/uber/plugins/uber/uber/models.py", line 164, in _invoke_adjustment_callbacks
       func()
     File "/usr/local/uber/plugins/uber/uber/models.py", line 936, in _cost_and_leader
       if not self.is_unpaid:
     File "/usr/local/uber/plugins/uber/uber/models.py", line 984, in is_unpaid
       return self.cost > 0 and self.amount_paid == 0
   TypeError: unorderable types: str() > int()
```

**Comment by RobRuana** [comment]
I believe this is actually directly related to #2519 – either `self.cost` or `self.amount_paid` were empty strings, which should be fixed by https://github.com/magfest/ubersystem/pull/2520
