### ISSUE TITLE
ERROR in production west

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2519]
```
   Traceback (most recent call last):
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 254, in with_session
       retval = func(*args, session=session, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 375, in with_restrictions
       return func(*args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 315, in with_rendering
       result = func(*args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 30, in with_check
       return func(*args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/site_sections/groups.py", line 58, in form
       raise HTTPRedirect('form?id={}&message={}', group.id, 'Group info uploaded')
   uber.utils.HTTPRedirect: (['https://west2017.uber.magfest.org/uber/groups/form?id=XXX&message=Group%20info%20uploaded'], 302)
   
   During handling of the above exception, another exception occurred:
   
   Traceback (most recent call last):
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
       context)
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
       cursor.execute(statement, parameters)
   psycopg2.DataError: invalid input syntax for integer: ""
   LINE 1: UPDATE "group" SET tables='0', cost='', auto_recalc=false WH...
                                               ^
   
   
   The above exception was the direct cause of the following exception:
   
   Traceback (most recent call last):
     File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
       response.body = self.handler()
     File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
       self.body = self.oldhandler(*args, **kwargs)
     File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
       return self.callable(*self.args, **self.kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 239, in with_timing
       return func(*args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 230, in with_caching
       return func(*args, **kwargs)
     File "/usr/local/uber/plugins/uber/uber/decorators.py", line 258, in with_session
       session.commit()
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 874, in commit
       self.transaction.commit()
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 461, in commit
       self._prepare_impl()
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
       self.session.flush()
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2139, in flush
       self._flush(objects)
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2259, in _flush
       transaction.rollback(_capture_exception=True)
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
       compat.reraise(exc_type, exc_value, exc_tb)
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
       raise value
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2223, in _flush
       flush_context.execute()
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
       rec.execute(self)
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
       uow
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
       mapper, table, update)
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/persistence.py", line 737, in _emit_update_statements
       execute(statement, multiparams)
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 945, in execute
       return meth(self, multiparams, params)
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
       return connection._execute_clauseelement(self, multiparams, params)
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
       compiled_sql, distilled_params
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
       context)
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
       exc_info
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
       reraise(type(exception), exception, tb=exc_tb, cause=cause)
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
       raise value.with_traceback(tb)
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
       context)
     File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
       cursor.execute(statement, parameters)
   sqlalchemy.exc.DataError: (psycopg2.DataError) invalid input syntax for integer: ""
   LINE 1: UPDATE "group" SET tables='0', cost='', auto_recalc=false WH...
                                               ^
    [SQL: 'UPDATE "group" SET tables=%(tables)s, cost=%(cost)s, auto_recalc=%(auto_recalc)s WHERE "group".id = %(group_id)s'] [parameters: {'group_id': UUID('XXX'), 'auto_recalc'…
```

**Comment by binary1230** [comment]
to repro, edit an existing group and set these two options like so:

![image](https://cloud.githubusercontent.com/assets/5413064/26738129/f2bcac92-479a-11e7-9ee9-6df2f4c300aa.png)
