### ISSUE TITLE
ERROR in AT_THE_CON mode checkin existing attendee

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2528]
In this page: https://staging2.uber.magfest.org/uber/registration, clicking the "Check In" button.

Looks like the same bug as here: https://github.com/magfest/ubersystem/issues/2527

**Comment by kitsuta** [comment]
```
Traceback (most recent call last):
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 240, in with_timing
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 231, in with_caching
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 255, in with_session
    retval = func(*args, session=session, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 376, in with_restrictions
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 341, in with_rendering
    return render(_get_template_filename(func), result)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 276, in render
    rendered = template.render(data)
  File "/usr/local/uber/env/lib/python3.4/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/uber/env/lib/python3.4/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/uber/env/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/uber/plugins/magstock/magstock/templates/registration/check_in_form.html", line 1, in top-level template code
    {% extends "registration/check_in_form_base.html" %}
  File "/usr/local/uber/plugins/uber/uber/templates/registration/check_in_form_base.html", line 5, in top-level template code
    {% block checkin_fields %}
  File "/usr/local/uber/plugins/magstock/magstock/templates/registration/check_in_form.html", line 30, in block "checkin_fields"
    {{ block.super }}
  File "/usr/local/uber/env/lib/python3.4/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'block' is undefined
```
