### ISSUE TITLE
dateparser path error occurs in pycharm debugger

### ISSUE THREAD

**Issue by migetman9** [magfest/ubersystem#2536]
Unable to run development sideboard, hitting the following stack trace:

```Traceback (most recent call last):
  File "/home/vagrant/uber/sideboard/sideboard/run_debug_server.py", line 2, in <module>
    from sideboard.debugging import debugger_helpers_all_init
  File "/home/vagrant/uber/sideboard/sideboard/__init__.py", line 16, in <module>
    _discover_plugins()
  File "/home/vagrant/uber/sideboard/sideboard/internal/imports.py", line 34, in _discover_plugins
    plugins[name] = importlib.import_module(name)
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/vagrant/uber/sideboard/plugins/uber/uber/__init__.py", line 4, in <module>
    from uber.common import *
  File "/home/vagrant/uber/sideboard/plugins/uber/uber/common.py", line 43, in <module>
    import dateparser
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/dateparser/__init__.py", line 4, in <module>
    from .date import DateDataParser
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/dateparser/date.py", line 11, in <module>
    from dateparser.date_parser import date_parser
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/dateparser/date_parser.py", line 10, in <module>
    from .conf import apply_settings
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/dateparser/conf.py", line 66, in <module>
    settings = Settings()
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/dateparser/conf.py", line 32, in __init__
    self._updateall(self._get_settings_from_yaml().items())
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/dateparser/conf.py", line 45, in _get_settings_from_yaml
    data = get_data('data', 'settings.yaml')
  File "/usr/lib/python3.4/pkgutil.py", line 629, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap>", line 1623, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/home/vagrant/uber/sideboard/data/settings.yaml'
```

I have attempted `./apply_node.sh localhost` `python setup.py develop` and entirely reinstalling Uber.

**Comment by migetman9** [comment]
According to @RobRuana that file should be located inside of dateparser, and should not be looking in `/home/vagrant/uber/sideboard/data/` https://github.com/scrapinghub/dateparser/blob/master/data/settings.yaml

**Comment by binary1230** [comment]
re-opening and renaming this issue, 

if running from inside the pycharm debugger, this error occurs anytime we do ```import dateparser```.  this seems to be ONLY a pycharm-specific thing and not a generic sideboard import issue.

it used to be that we did that on import on startup so crashed the debugger.  now, it only happens when you hit ```import dateparser```, which happens only in specific situations (like hitting the 'add band' button)

**Comment by binary1230** [comment]
i would consider this semi-low priority, even though it's annoying for pycharm users

**Comment by RobRuana** [comment]
Ok, this is the third time we've had issues with `dateparser` so I am definitely going to remove it.
