### ISSUE TITLE
Unassigning an Attendee group badge with a pre-assigned number violates unique constraint

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#2823]
I was trying to reproduce a different error in staging, an got this (all data is fake):
```
Traceback (most recent call last):
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 267, in with_session
    retval = func(*args, session=session, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 388, in with_restrictions
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 328, in with_rendering
    result = func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 95, in protected
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/site_sections/registration.py", line 287, in delete
    raise HTTPRedirect(return_to + ('' if return_to[-1] == '?' else '&') + 'message={}', message)
uber.utils.HTTPRedirect: (['https://staging4.uber.magfest.org/uber/groups/form?id=a2a85d5f-2a5c-4da7-a07b-51fb02864b33&message=Attendee%20deleted%2C%20but%20this%20badge%20is%20still%20available%20to%20be%20assigned%20to%20someone%20else%20in%20the%20same%20group'], 302)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 721, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 443, in do_commit
    dbapi_connection.commit()
psycopg2.IntegrityError: duplicate key value violates unique constraint "uq_attendee_badge_num"
DETAIL:  Key (badge_num)=(15793) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 252, in with_timing
    return func(*args, **kwargs)
  File "/usr/local/uber/plugins/uber/uber/decorators.py", line 271, in with_session
    session.commit()
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 906, in commit
    self.transaction.commit()
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 465, in commit
    t[1].commit()
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1632, in commit
    self._do_commit()
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1663, in _do_commit
    self.connection._commit_impl()
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 723, in _commit_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 721, in _commit_impl
    self.engine.dialect.do_commit(self.connection)
  File "/usr/local/uber/env/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 443, in do_commit
    dbapi_connection.commit()
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "uq_attendee_badge_num"
DETAIL:  Key (badge_num)=(15793) already exists.
```

**Comment by RobRuana** [comment]
This is very similar to the bug we dealt with in [this issue](https://github.com/magfest/ubersystem/issues/2675), only it's manifesting from a different place in the code. I explained why the previous bug was happening [here](https://github.com/magfest/ubersystem/pull/2718#discussion_r128908448), but this version of the bug is actually the inverse situation...

# The Issue

Here is the actual cause of the bug. Imagine you have a group with 4 members, all marked as staff badges. Starts out looking something like this:

Badge Number | Existing Attendees
------------ | --------
\# 10 | Leader
\# 11 | Alice
\# 12 | Bob
\# 13 | Charlie

The leader wants to remove Bob from her group members. She clicks the "Unassign" button. Charlie will then be shifted down to claim badge  \# 12. 

Badge Number | Existing Attendees | Changes
------------ | -------- | --
\# 10 | Leader |
\# 11 | Alice | 
\# 12 | (Bob will be deleted) | Charlie wants to claim \# 12
\# 13 | (Charlie will be shifted) |

So what happens? Well, what happens when we unassign a group badge? We create a duplicate "Unassigned" badge! So "Unassigned" gets badge \# 12, AND the Charlie gets badge \# 12!

Badge Number | Existing Attendees | New Attendees
------------ | -------- | --
\# 10 | Leader |
\# 11 | Alice | 
\# 12 | Charlie (shifted down) | Unassigned wants to claim \# 12

Charlie is saved, and the database complains because both the Charlie and "Unassigned" have the badge \# 12.

# The Fix

To fix the previous bug, instead of deleting the existing unassigned attendee, we simply updated its properties with the submitted values. I'm not certain we can do that here, because the newly created "Unassigned" badge would have the same id, and Bob could then reuse the old link to reclaim it.

In this case, we _could_ add a `skip_badge_num_shift` property to the `Session`. If the `skip_badge_num_shift` flag is set, then we don't shift badge numbers. It would be relatively safe for this particular case, because we know we're creating another badge with the same number as the one we're deleting.

Thoughts?

**Comment by kitsuta** [comment]
Hmm, that would work but might be a bit overkill. Would it be simpler to just not attempt to transfer their badge number over? Their badge number would change, which might not be ideal, but it might be acceptable.

**Comment by RobRuana** [comment]
Oh, that would probably also work. I guess it depends on how important keeping the same badge number would be – both for consistency and to keep group badge numbers clumped together.

I suppose I prefer keeping the badge number the same because that's the ideal outcome. Like, as a user of the system that is how I would expect it to work. And it's not just one badge that gets a new number, it's every badge above it.

The badge shifting code is somewhat expensive, so it's advantageous to skip it when we can. I suppose the `skip_badge_num_shift` flag feels a little janky. But I also think it's okay to be able to configure how the badge shifting algorithm works.

That being said, I am totally okay with just not transferring the badge number! This isn't a sweeping redesign, so I don't have super strong opinions on it 😄

**Comment by kitsuta** [comment]
What a coincidence, I also don't have strong feelings on it!
