### ISSUE TITLE
As a developer, I would like to see the original exception from a model @property

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2842]
If one of our model @properties throws an exception, for example `total_cost`, then the `__getattr__()` handler is invoked, which inevitably raises an `AttributeError`. So it looks like there's no attribute named `total_cost`, while in reality `total_cost` raised an exception when it was invoked, but the exception is completely swallowed and it's impossible to discern what went wrong.

```
Traceback (most recent call last):
      File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
        response.body = self.handler()
      File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 220, in __call__
        self.body = self.oldhandler(*args, **kwargs)
      File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
        return self.callable(*self.args, **self.kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 252, in with_timing
        return func(*args, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 267, in with_session
        retval = func(*args, session=session, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 388, in with_restrictions
        return func(*args, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 328, in with_rendering
        result = func(*args, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 30, in with_check
        return func(*args, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/site_sections/registration.py", line 103, in form
        message = check(attendee)
      File "/usr/local/uber/plugins/uber/uber/utils.py", line 128, in check
        message = validator(model)
      File "/usr/local/uber/plugins/uber/uber/model_checks.py", line 153, in reasonable_total_cost
        if attendee.total_cost >= 999999:
      File "/usr/local/uber/plugins/uber/uber/models.py", line 494, in __getattr__
        raise AttributeError(self.__class__.__name__ + '.' + name)
    AttributeError: Attendee.total_cost
```

**Comment by RobRuana** [comment]
Something like this works:

```python
def safe_property(func):
    @functools.wraps(func)
    def wrapped(*args, **kwargs):
        error_message = None
        try:
            return func(*args, **kwargs)
        except AttributeError as err:
            # Don't reraise the error inside the exception handler, otherwise
            # we get both the original error and the RuntimeError with a 
            # message saying: "During handling of the above exception, another 
            # exception occurred:"
            error_message = '{} failed with an AttributeError: {}'.format(
                func.__name__, err)
        if error_message:
            raise RuntimeError(error_message)
    return property(wrapped)
```

And then we change the properties in our model classes to use `@safe_property` instead of `@property`

**Comment by thaeli** [comment]
Would this be a blanket replace or are there some places in models that we
would still want to use the bare @property?

**Comment by RobRuana** [comment]
@thaeli I think this would have to be a blanket replace for any of our classes that use `__getattr__` (which is all of our model classes). There's a lot of articles out there about the danger of using both `__getattr__` and `@property` in the same class.

It boils down to the fact that if a `@property` raises an `AttributeError` it's completely swallowed by `__getattr__`, and there's no way to extract the original exception. I've tried being clever with the `sys` module, the `traceback` module, and the `inspect` module to no avail. The exception is completely cleared at the CPython level 😢

**Comment by RobRuana** [comment]
The other option would be to implement both `__getattr__` _and_ `__getattribute__`, but I'm worried that would introduce even more magic that would be hard for new developers to digest.

**Comment by RobRuana** [comment]
lol, closing as a duplicate of #1942
