### ISSUE TITLE
ERROR: Couple bugs in production

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2875]
```
   Traceback (most recent call last):
      File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
        response.body = self.handler()
      File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 221, in __call__
        self.body = self.oldhandler(*args, **kwargs)
      File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
        return self.callable(*self.args, **self.kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 252, in with_timing
        return func(*args, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 263, in with_session
        return func(*args, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 388, in with_restrictions
        return func(*args, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 328, in with_rendering
        result = func(*args, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/site_sections/preregistration.py", line 23, in wrapped
        return func(self, *args, **kwargs)
    TypeError: not_found() missing 1 required positional argument: 'message'
```

```
   Traceback (most recent call last):
      File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
        response.body = self.handler()
      File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 221, in __call__
        self.body = self.oldhandler(*args, **kwargs)
      File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
        return self.callable(*self.args, **self.kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 252, in with_timing
        return func(*args, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 267, in with_session
        retval = func(*args, session=session, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 388, in with_restrictions
        return func(*args, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 353, in with_rendering
        return render(_get_template_filename(func), result)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 288, in render
        rendered = template.render(data)
      File "/usr/local/uber/env/lib/python3.4/site-packages/jinja2/environment.py", line 1008, in render
        return self.environment.handle_exception(exc_info, True)
      File "/usr/local/uber/env/lib/python3.4/site-packages/jinja2/environment.py", line 780, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/usr/local/uber/env/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
        raise value.with_traceback(tb)
      File "/usr/local/uber/plugins/uber/uber/templates/preregistration/form.html", line 1, in top-level template code
        {% extends "./preregistration/preregbase.html" %}
      File "/usr/local/uber/plugins/uber/uber/templates/preregistration/preregbase.html", line 1, in top-level template code
        {% extends "base.html" %}
      File "/usr/local/uber/plugins/uber/uber/templates/base.html", line 285, in top-level template code
        {% block content %}{% endblock %}
      File "/usr/local/uber/plugins/uber/uber/templates/preregistration/form.html", line 59, in block "content"
        {% include "regform.html" %}
      File "/usr/local/uber/plugins/uber/uber/templates/regform.html", line 392, in top-level template code
        <input type='text' class="form-control date" name="birthdate" value="{{ attendee.birthdate|datetime("%Y-%m-%d") }}"/>
      File "/usr/local/uber/plugins/uber/uber/custom_tags.py", line 43, in datetime_filter
        return '' if not dt else ' '.join(dt.strftime(fmt).split()).replace('AM', 'am').replace('PM', 'pm')
    AttributeError: 'str' object has no attribute 'strftime'
```

**Comment by RobRuana** [comment]
The first stack trace above is probably an error we want to fix. 

The second stack trace is the result of a spam-bot POSTing garbage data. Specifically a non-date string in the `birthdate` field. I don't think we need to fix that. In fact, there's not much we can do. POSTing bad data is always going to have a bad result.
