### ISSUE TITLE
ERROR: Looks like a legit error in production?

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#2880]
```
2017-10-03 17:21:31,526 [ERROR] uber.server:
    Exception encountered
    Request: POST /uber/registration/assign HTTP/1.0
    Request Headers:
      Content-Type: application/x-www-form-urlencoded
      ORIGIN: https://super2018.uber.magfest.org
      Content-Length: 91
      REFERER: https://super2018.uber.magfest.org/uber/registration/shifts?id=XXX
      ACCEPT-ENCODING: gzip, deflate, br
      ACCEPT-LANGUAGE: en-US,en;q=0.8
      X-FORWARDED-PROTO: https
      USER-AGENT: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
      CACHE-CONTROL: max-age=0
      UPGRADE-INSECURE-REQUESTS: 1
      HOST: super2018.uber.magfest.org
      ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
      CONNECTION: close
    Traceback (most recent call last):
      File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
        response.body = self.handler()
      File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 221, in __call__
        self.body = self.oldhandler(*args, **kwargs)
      File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
        return self.callable(*self.args, **self.kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 252, in with_timing
        return func(*args, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 267, in with_session
        retval = func(*args, session=session, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 388, in with_restrictions
        return func(*args, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 328, in with_rendering
        result = func(*args, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 95, in protected
        return func(*args, **kwargs)
    TypeError: assign() missing 1 required positional argument: 'job_id'
```

**Comment by RobRuana** [comment]
This happens if you click the "assign" button without anything selected.

![screenshot_20171003-173452](https://user-images.githubusercontent.com/2592431/31151369-2a0babdc-a865-11e7-8d22-86d2eb7bc140.png)

**Comment by binary1230** [comment]
Actually not just that nothing was selected but there was nothing in that drop down list at all.

We should probably gray out the button if there's nothing in the list, or something.


Kind of a low priority monkey test bug tho
