### ISSUE TITLE
verbose error handler can itself throw errors for file uploads

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#2945]
Rob and I discussed this, had an exception raised:

```
2017-11-13 12:12:42,779 [ERROR] cherrypy.error.140684693618304: [13/Nov/2017:12:12:42]  
   Traceback (most recent call last):
      File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
        response.body = self.handler()
      File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 221, in __call__
        self.body = self.oldhandler(*args, **kwargs)
      File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
        return self.callable(*self.args, **self.kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 382, in with_timing
        return func(*args, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 397, in with_session
        retval = func(*args, session=session, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 518, in with_restrictions
        return func(*args, **kwargs)
      File "/usr/local/uber/plugins/uber/uber/decorators.py", line 458, in with_rendering
        result = func(*args, **kwargs)
      File "/usr/local/uber/plugins/mivs/mivs/site_sections/mivs_applications.py", line 270, in show_info
        with open(screenshot.filepath, 'wb') as f:
    NameError: name 'screenshot' is not defined
```

Ignore the particulars of that above exception.   The part we're interested in is, our exception handling code (which attempts to log extra information about the request/session/etc) itself failed while parsing the request params with this message:

```

   During handling of the above exception, another exception occurred:
    
   Traceback (most recent call last):
      File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 589, in run
        self.respond(pi)
      File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 690, in respond
        self.handle_error()
      File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 765, in handle_error
        self.hooks.run('before_error_response')
      File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 114, in run
        raise exc
      File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 104, in run
        hook()
      File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 63, in __call__
        return self.callback(**self.kwargs)
      File "/usr/local/uber/plugins/uber/uber/server.py", line 50, in log_exception_with_verbose_context
        log_with_verbose_context('\n'.join([msg, 'Exception encountered']), exc_info=True)
      File "/usr/local/uber/plugins/uber/uber/server.py", line 41, in log_with_verbose_context
        full_msg = '\n'.join([msg, get_verbose_request_context()])
      File "/usr/local/uber/plugins/uber/uber/server.py", line 29, in get_verbose_request_context
        p = ["  %s: %s" % (k, v[:max_reporting_length]) for k, v in cherrypy.request.params.items()]
      File "/usr/local/uber/plugins/uber/uber/server.py", line 29, in <listcomp>
        p = ["  %s: %s" % (k, v[:max_reporting_length]) for k, v in cherrypy.request.params.items()]
    TypeError: 'Part' object is not subscriptable
```

When the error-handling code crashes, that's not great :) .  Luckily, it still prints the original exception (without the extra useful context though).

We should prob write a unit test for our exception handling code to mock and repro this error, and then fix the bug after.

**Comment by binary1230** [comment]
Good news is, this can be pretty low-priority because at least the error (even with the exception handler crashing) is still reported via our logging system, so we're not losing the original exception.

This shit keeps me up at night : )
