### ISSUE TITLE
Error sending emails to placeholder attendees without first or last name

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#3010]
```
2017-12-08 20:41:51,576 [ERROR] uber.automated_emails_server.StopsEmail: error sending 'MAGFest Volunteer Badge Confirmation' email to XXX@example.com
    Traceback (most recent call last):
      File "/usr/local/uber/plugins/uber/uber/automated_emails_server.py", line 172, in really_send
        model=model_instance, cc=self.cc, ident=self.ident)
      File "/usr/local/uber/plugins/uber/uber/utils.py", line 241, in send_email
        message=message
      File "/usr/local/uber/plugins/uber/uber/amazon_ses.py", line 101, in sendEmail
        return self._performAction('SendEmail', params)
      File "/usr/local/uber/plugins/uber/uber/amazon_ses.py", line 62, in _performAction
        return self._responseParser.parse(actionName, response.status, response.reason, responseResult)
      File "/usr/local/uber/plugins/uber/uber/amazon_ses.py", line 246, in parse
        self._raiseError(xmlResponse)
      File "/usr/local/uber/plugins/uber/uber/amazon_ses.py", line 237, in _raiseError
        raise AmazonError(errorType, code, message)
    uber.amazon_ses.AmazonError: ('Sender', 'InvalidParameterValue', 'Domain contains control or whitespace')
```

**Comment by RobRuana** [comment]
After some inspection, it seems the email address in question had a control character at the end: `XXX@example.com\u200b`
