### ISSUE TITLE
ERROR: Creating a new one day badge throws an error

### ISSUE THREAD

**Issue by RobRuana** [magfest/ubersystem#3028]
The ultimate cause of this error is that the `_misc_adjustments()` `@presave_adjustment` fires before `self.registered` is set. The `self.registered` time is used to calculate the price of the one day badge:

https://github.com/magfest/ubersystem/blob/01d40567dff40a233c89d357d4736e8c9ebafe8a/uber/models/attendee.py#L464

I propose changing the line from:

```python
registered = self.registered_local if self.registered else None
```

to:

```python
registered = self.registered_local if self.registered else datetime.utcnow().replace(tzinfo=pytz.UTC)
```

# Traceback
```
Traceback (most recent call last):
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/vagrant/uber/sideboard/plugins/uber/uber/decorators.py", line 382, in with_timing
    return func(*args, **kwargs)
  File "/home/vagrant/uber/sideboard/plugins/uber/uber/decorators.py", line 401, in with_session
    session.commit()
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 906, in commit
    self.transaction.commit()
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2171, in flush
    self._flush(objects)
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/sqlalchemy/orm/session.py", line 2198, in _flush
    self.dispatch.before_flush(self, flush_context, objects)
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/sqlalchemy/event/attr.py", line 218, in __call__
    fn(*args, **kw)
  File "/home/vagrant/uber/sideboard/plugins/uber/uber/models/__init__.py", line 1405, in _presave_adjustments
    model.presave_adjustments()
  File "/home/vagrant/uber/sideboard/plugins/uber/uber/models/__init__.py", line 81, in presave_adjustments
    self._invoke_adjustment_callbacks('presave_adjustment')
  File "/home/vagrant/uber/sideboard/plugins/uber/uber/models/__init__.py", line 78, in _invoke_adjustment_callbacks
    function()
  File "/home/vagrant/uber/sideboard/plugins/uber/uber/models/attendee.py", line 292, in _misc_adjustments
    self.base_badge_price = self.new_badge_cost
  File "/home/vagrant/uber/sideboard/plugins/uber/uber/models/__init__.py", line 355, in __getattr__
    raise AttributeError(self.__class__.__name__ + '.' + name)
AttributeError: Attendee.new_badge_cost
```

**Comment by RobRuana** [comment]
Ugh, just realized, my initial proposal doesn't do what we want. We have no way specifying _which day_ the one day badge is for. If we just use today's date, it could very well be the wrong day of week.

**Comment by earl7399** [comment]
We don't do one-day badges @ Prime, so can this wait until after?

--
Bob Earl <r.a.earl@gmail.com>
FAX: +1 440 919 5086

**Comment by RobRuana** [comment]
Yep, not planning on fixing it right now. It's a little annoying that we still have the "One Day" option on the admin side, though.
