### ISSUE TITLE
API error when trying to log unicode data

### ISSUE THREAD

**Issue by binary1230** [magfest/ubersystem#3126]
seeing these:

--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.4/logging/__init__.py", line 980, in emit
    stream.write(msg)

it's because of:

UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f4a9' in position 3048: ordinal not in range(128)
Call stack:
  File "/usr/lib/python3.4/threading.py", line 888, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/uber/sideboard/lib/_threads.py", line 61, in _thread_name_insert
    threading.Thread._bootstrap_inner_original(self)
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/local/uber/env/lib/python3.4/site-packages/cheroot/workers/threadpool.py", line 109, in run
    conn.communicate()
  File "/usr/local/uber/env/lib/python3.4/site-packages/cheroot/server.py", line 1152, in communicate
    req.respond()
  File "/usr/local/uber/env/lib/python3.4/site-packages/cheroot/server.py", line 974, in respond
    self.server.gateway(self).respond()
  File "/usr/local/uber/env/lib/python3.4/site-packages/cheroot/wsgi.py", line 131, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cptree.py", line 297, in __call__
    return app(environ, start_response)
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cptree.py", line 155, in __call__
    return self.wsgiapp(environ, start_response)
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpwsgi.py", line 451, in __call__
    return head(environ, start_response)
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpwsgi.py", line 154, in __call__
    self.throws
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpwsgi.py", line 169, in __init__
    self.nextapp, self.environ, self.start_response,
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpwsgi.py", line 190, in trap
    return func(*args, **kwargs)
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpwsgi.py", line 106, in __call__
    return self.nextapp(environ, start_response)
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpwsgi.py", line 439, in 

...snip...

  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/uber/sideboard/jsonrpc.py", line 21, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/usr/local/uber/env/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/local/uber/sideboard/jsonrpc.py", line 86, in jsonrpc_handler
    log.debug('returning success message: {!r}', response)
Message: 'returning success message: {!r}'

Arguments: { - removed by dom personal info, something in here causing issues - }

**Comment by binary1230** [comment]
i think as someone noted in slack, we just need to do some kind of unicode converstion at that debug.log()

that does mean each stream.write issue we're seeing has been failing the API request.

**Comment by EliAndrewC** [comment]
Amusingly, the character is question is 💩 which looks like the poop emoji.

At a glance, it looks like this error is occurring (according to the stacktrace) when we try to log the poop emoji, which seems like it should be okay since that in general.

```python
root@rams1:~# magpy
Python 3.4.3 (default, Nov 28 2017, 16:41:13) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> d = {'fake': 'jsonrpc dict to log', 'problematic character': '\U0001f4a9'}
>>> print(d)
{'fake': 'jsonrpc dict to log', 'problematic character': '💩'}
>>> log.info('log messages seem to work even with {!r}', d)
2018-01-06 11:53:45,756 [INFO] __main__: log messages seem to work even with {'fake': 'jsonrpc dict to log', 'problematic character': '💩'}
```

**Comment by binary1230** [comment]
it's from @waffles 's entry : )

**Comment by binary1230** [comment]
it's trying to dump this API request to the log:

'job': {'department_name': 'LAN', 'description': 'I CAME IN LIKE A WRECKING BALL (and fiber spooling)', '_model': 'Job', 'start_time': datetime.datetime(2018, 1, 7, 23, 0, tzinfo=<UTC>), 'name': 'LAN Demolition \U0001f4a9', 'id': 'ba32eb5c-88fe-489a-b35e-17a50ae3f0c0', 'type_label': 'Teardown', 'end_time': datetime.datetime(2018, 1, 8, 5, 0, tzinfo=<UTC>), 'extra15': False},

**Comment by RobRuana** [comment]
So that's in his work history. I am going to manually change that character in the database so we stop getting these errors. We can circle back and fix this for real post-event.

**Comment by RobRuana** [comment]
Replaced offending characters with `<POOP_EMOJI>`
