### ISSUE TITLE
500 error for new attendees registering

### ISSUE THREAD

**Issue by kitsuta** [magfest/ubersystem#924]
When a new attendee tries to register on the registration/register page, they get this:

```
Traceback (most recent call last):
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/CherryPy-3.6.0-py3.4.egg/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/CherryPy-3.6.0-py3.4.egg/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/vagrant/uber/sideboard/env/lib/python3.4/site-packages/CherryPy-3.6.0-py3.4.egg/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/vagrant/uber/sideboard/plugins/uber/uber/decorators.py", line 122, in with_session
    retval = func(*args, session=session, **kwargs)
  File "/home/vagrant/uber/sideboard/plugins/uber/uber/decorators.py", line 212, in with_restrictions
    return func(*args, **kwargs)
  File "/home/vagrant/uber/sideboard/plugins/uber/uber/decorators.py", line 182, in with_rendering
    result = func(*args, **kwargs)
  File "/home/vagrant/uber/sideboard/plugins/uber/uber/site_sections/registration.py", line 368, in register
    attendee.save()
  File "/home/vagrant/uber/sideboard/plugins/uber/uber/models.py", line 154, in __getattr__
    raise AttributeError(self.__class__.__name__ + '.' + name)
AttributeError: Attendee.save
```

**Comment by EliAndrewC** [comment]
Seems bad!  I'll take a look tonight.

In general, most of the at-the-con-only stuff hasn't been tested yet, so it's not surprising that there are a few things which are still broken :(

**Comment by kitsuta** [comment]
Too late

Already fixed it
